[tools]
java = "openjdk-22.0.2"
node = "latest"
yarn = "latest"
pnpm = "latest"
youtube-dl = "latest"
act = "latest"
zoxide = "latest"
python = "latest"
lazygit = "latest"
bat = "latest"
age = "latest"
go = "latest"
deno = "latest"
bun = "latest"
azure-cli = "latest"
