#!/usr/bin/env python3
import os
import subprocess as sp
import json

def mute_toggle():
    sp.run(["dunstctl", "set-paused", "toggle"], check=True)

def clicked():
    button = os.environ.get("BLOCK_BUTTON", None)
    return bool(button)

def muted():
    output = sp.check_output(('dunstctl', 'is-paused'))
    return u'true' ==  output.strip().decode("UTF-8")

if clicked():
    # toggle button click to turn mute on and off
    mute_toggle()

if muted():
    RTN = {"full_text":"<span font='Font Awesome 5 Free Solid' color='#BE616E'>\uf1f6</span>"}
else:
    RTN = {"full_text":"<span font='Font Awesome 5 Free Solid' color='#A4B98E'>\uf0f3</span>"}

print(json.dumps(RTN))
